name: ydnpd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - plotly
  - sdv
  - nbformat
  - pandera
  - ipywidgets
  - pip:
    - wandb
    - weave
    - ray[default]
    - smartnoise-synth
    - git+https://github.com/ryan112358/private-pgm.git
    - SciencePlots
    - pyro-ppl
    - openai
    - python-statemachine
    - ydata_profiling
    # - synthcity
