name: ydnpd
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - sdv
  - pip:
    - wandb
    - ray[default]
    - smartnoise-synth
    - git+https://github.com/ryan112358/private-pgm.git
    - SciencePlots
    # - synthcity
